In [3]:
from pydataset import data
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [12]:
df = data("DoctorAUS")
X = df[['age', 'income', 'sex', 'illness', 'actdays', 'hscore', 'doctorco', 'nondocco', 'hospadmi', 'hospdays', 'medecine', 'prescrib']]
y = df['insurance']
df

,sex,age,income,insurance,illness,actdays,hscore,chcond,doctorco,nondocco,hospadmi,hospdays,medecine,prescrib,nonpresc
1,1,0.19,0.55,levyplus,1,4,1,np,1,0,0,0,1,1,0
2,1,0.19,0.45,levyplus,1,2,1,np,1,0,0,0,2,1,1
3,0,0.19,0.90,medlevy,3,0,0,np,1,0,1,4,2,1,1
4,0,0.19,0.15,medlevy,1,0,0,np,1,0,0,0,0,0,0
5,0,0.19,0.45,medlevy,2,5,1,la,1,0,0,0,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5186,1,0.22,0.55,medlevy,0,0,0,np,0,0,0,0,0,0,0
5187,0,0.27,1.30,medlevy,0,0,1,np,0,0,0,0,3,0,3
5188,1,0.37,0.25,freerepa,1,0,1,np,0,0,0,0,0,0,0
5189,1,0.52,0.65,medlevy,0,0,0,np,0,0,0,0,0,0,0
5190,0,0.72,0.25,freerepa,0,0,0,np,0,0,0,0,0,0,0

### Splitting thd data

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=0)

### Model training

In [14]:
clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB()

### Model evaluating

In [15]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

     freepor       0.29      0.12      0.16        69
    freerepa       0.63      0.52      0.57       321
    levyplus       0.50      0.31      0.39       670
     medlevy       0.48      0.81      0.60       497

    accuracy                           0.51      1557
   macro avg       0.47      0.44      0.43      1557
weighted avg       0.51      0.51      0.48      1557